icons = "awesome"

[theme]
name = "gruvbox-dark"
[theme.overrides]
idle_bg = "#1d1f21"
idle_fg = "#b4b7b4"
good_bg = "#0A4F72"


[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug} GB"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
signal_strength = false
speed_up = false
speed_down = false
interval = 5
use_bits = false

[[block]]
block = "battery"
driver = "upower"
device = "DisplayDevice"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

